/**
 * SnapGames
 * 
 * Game Development Java
 * 
 * gdj105
 * 
 * @year 2018
 */
package com.snapgames.gdj.core.gfx;

import java.awt.image.BufferedImage;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 
 * @author Frédéric Delorme
 *
 */
public class Sprite {

	private static int index = 0;

	int id;
	String name;
	BufferedImage pixels;
	Map<String, Object> attributes = new ConcurrentHashMap<>(10);

	/**
	 * Initialize the new Sprite with the pixels and name. The id filed will be
	 * autogenerated from index.
	 * 
	 * @param pixels
	 * @param name
	 */
	public Sprite(BufferedImage pixels, String name) {
		this.id = index++;
		this.name = name;
		this.pixels = pixels;
	}

	/**
	 * Initialize the new Sprite with the id, pixels and name.
	 * 
	 * @param id
	 * @param pixels
	 * @param name
	 */
	public Sprite(int id, BufferedImage pixels, String name) {
		this.id = id;
		this.name = name;
		this.pixels = pixels;
	}

	public void addAttribute(String key, Object value) {
		assert (!attributes.containsKey(key));
		attributes.put(key, value);
	}

	public Object getAttributze(String key) {
		assert (attributes.containsKey(key));
		return attributes.get(key);
	}

	public BufferedImage getImage() {
		// TODO Auto-generated method stub
		return pixels;
	}

}
